### ISSUE TITLE
The insufficient funds aren't calculated if  in the wallet has shielded coins on the send screen

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#163]
The insufficient funds aren't calculated if  in the wallet has shielded coins on the send screen

Precondition:
In wallet has shielded and regular coins

Step:

- go to send screen
- in the amount field, enter value more than has in the wallet

Expected: insufficient funds are calculated 
Actual: insufficient funds aren't calculated 

Build: 5.0.9519.3128
![Screenshot_136](https://user-images.githubusercontent.com/50007056/91719142-71ceea00-eb9d-11ea-971a-3c3f8b0ee8c3.png)

**Comment by echoby** [comment]
fixed at commit 8e975c8

**Comment by Roberrtt** [comment]
Align the text when the amount entered is more than the amount in wallet
build 5.0.9544.3157
![Screenshot_158](https://user-images.githubusercontent.com/50007056/92359904-ab9b7580-f0f4-11ea-8a17-be1de7eda31c.png)

**Comment by Roberrtt** [comment]
2 - not fixed
When we copy the entire amount on the wallet screen and insert it in amount field on the send screen. Then when you click on the "add all" button, the amount doesn't change
![bandicam-2020-09-07-17-17-54-578](https://user-images.githubusercontent.com/50007056/92397201-14074880-f12f-11ea-9290-effaf63582fc.gif)

**Comment by Roberrtt** [comment]
checked
